version: "3.8"
services:
  api:
    build:
      context: .
      # Correct the path to your Dockerfile
      dockerfile: Dockerfile.dev
    ports:
      - 8080:8080
    # Important to bind/mount your codebase dir to /app dir for live reload
    volumes:
      - ./:/app
